---
- name: Refresh package lists
  apt:
    update_cache: yes
  tags: essential-packages

- name: Install some essential packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - apt-transport-https
  - build-essential
  - ca-certificates
  - curl
  - git-core
  - graphviz
  - lsb-release
  - python-mysqldb
  - python-passlib
  - python-psycopg2
  - python-pycurl
  - python3-software-properties
  - sudo
  - vim
  tags: essential-packages
