---
- name: Create groups
  group:
    name: "{{ item }}"
    state: present
  with_items:
    "{{ user_groups }}"

- name: Create users
  user:
    name: "{{ item.name }}"
    group: "{{ item.groups[0] }}"
    groups: "{{ item.groups }}"
    state: present
    shell: /bin/bash
  with_items:
    "{{ users }}"
