---
- name: Authenticate with docker registry
  docker_login:
    url: "{{ current_app.login.url | default('https://index.docker.io/v1/')}}"
    email: "{{ current_app.login.email | default(None) }}"
    username: "{{ current_app.login.username }}"
    password: "{{ current_app.login.password }}"
  when: "{{ 'login' in current_app and 'username' in current_app.login and 'password' in current_app.login }}"

- name: Create docker networks
  docker_network:
    name: "{{ item }}"
  loop: "{{ docker_networks }}"

- name: Bring up docker container
  docker_container:
    state: started
    pull: True
    name: "{{ app_name }}"
    image: "{{ current_app.image }}"
    restart_policy: "{{ current_app.restart | default(True) }}"
    ports: "{{ current_app.ports | default([]) }}"
    links: "{{ current_app.links | default([]) }}"
    volumes: "{{ current_app.volumes | default([]) }}"
    env: "{{ current_app.env | default({}) }}"
    networks: "{{ current_app.networks | default([]) }}"
    entrypoint: "{{ current_app.entrypoint | default([]) }}"
    capabilities: "{{ current_app.capabilities | default([]) }}"

- import_tasks: post-deploy-docker.yml

