---
- name: Authenticate with docker registries
  docker_login:
    url: "{{ item.url | default('https://index.docker.io/v1/')}}"
    email: "{{ item.email | default(None) }}"
    username: "{{ item.username }}"
    password: "{{ item.password }}"
  loop: "{{ docker_registries | default([]) }}"

- name: Create docker networks
  docker_network:
    name: "{{ item }}"
  loop: "{{ docker_networks }}"

- name: Bring up docker container
  docker_container:
    state: started
    pull: True
    name: "{{ app_name }}"
    image: "{{ current_app.image }}"
    restart_policy: "{{ current_app.restart | default(True) }}"
    ports: "{{ current_app.ports | default([]) }}"
    links: "{{ current_app.links | default([]) }}"
    volumes: "{{ current_app.volumes | default([]) }}"
    env: "{{ current_app.env | default({}) }}"
    networks: "{{ current_app.networks | default({}) }}"
