---
- include: start.yml
- include: clone.yml
- include: files.yml
  when: current_app.is_laravel | default(True)
- include: env.yml
  when: current_app.env is defined | default(False)
- include: composer.yml
  when: current_app.is_laravel | default(True)
- include: passport.yml
  when: "'passport' in current_app and current_app.passport == True"
- include: maintenance.yml
  when: current_app.is_laravel | default(True)
- include: migrate.yml
  when: current_app.is_laravel | default(True)
- include: optimize.yml
  when: current_app.is_laravel | default(True)
- include: finish.yml
- include: restart-workers.yml
