---
- include: deploy-laravel.yml
  when: current_app.type is not defined or current_app.type == 'laravel'
- include: deploy-spa.yml
  when: current_app.type is defined and current_app.type == 'spa'
- include: deploy-docker.yml
  when: current_app.type is defined and current_app.type == 'docker'
