- src: nickhammond.logrotate
  version: master
- src: geerlingguy.composer
  version: 1.6.1
- src: geerlingguy.docker
  version: 2.5.1
- src: geerlingguy.ntp
  version: 1.5.2
- src: kamaln7.swapfile
  version: master
