---
- name: Create logs folder of sites
  file:
    path: "{{ webroot }}/{{ item.key }}/logs"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0755
    state: directory
  with_dict: "{{ apps }}"
