---
- include: self-signed-certificate.yml
  tags: certs
- include: folders.yml
- include: nginx.yml
- include: cron.yml
  when: "{{ item.value.is_laravel | default(True) }}"
- include: workers.yml
- include: reload-nginx.yml
