---
- import_tasks: self-signed-certificate.yml
  tags: certs
- import_tasks: folders.yml
- import_tasks: nginx-includes.yml
- import_tasks: nginx.yml
- import_tasks: cron.yml
- import_tasks: workers.yml
- import_tasks: reload-nginx.yml
