---
- name: Generate self-signed certificates
  shell: >
    openssl req -subj "/CN={{ item.value.hosts[0].canonical }}" -new
    -newkey rsa:2048 -days 3650 -nodes -x509 -sha256
    -keyout {{ item.key }}.key -out {{ item.key }}.cert
  args:
    chdir: "{{ nginx_path }}/ssl"
    creates: "{{ item.key }}.*"
  with_dict: "{{ apps }}"
  when: item.value.ssl.enabled and item.value.ssl.provider | default('manual') == 'self-signed'
  notify:
    - reload nginx
