---
- name: Create supervisor config directory
  file:
    path: "/etc/supervisor/conf.d/"
    state: directory

- name: Set up queue workers
  template:
    src: queue.conf
    dest: "/etc/supervisor/conf.d/{{ item.key }}.conf"
  with_dict: "{{ apps }}"
  when: "{{ 'workers' in item.value }}"