---
#-------------------------------------------------------------------------------
# Network Settings
#-------------------------------------------------------------------------------

# Additional open ports (besides 22, 80 & 443)
open_ports: []
