---
users:
  - name: "{{ web_user }}"
    groups:
      - "{{ web_group }}"
    keys:
      - "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      # - https://github.com/jsphpl.keys

web_user: web
web_group: www-data
web_sudoers:
  - "/usr/sbin/service php{{php_version}}-fpm *"
