---
- name: Make sure ruby and the build dependencies for our gem are present
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - ruby
    - ruby-dev
    - autoconf
    - binutils-doc
    - bison
    - build-essential
    - flex
    - gettext
    - ncurses-dev
    - zlib1g-dev

- name: Install the 'backup' gem
  gem:
    name: backup
    state: present
    user_install: false
    version: 5.0.0.beta.2
