---
- name: Install key for MariaDB repository (Ubuntu)
  apt_key:
    keyserver: "hkp://keyserver.ubuntu.com:80"
    id: "0xF1656F24C74CD1D8"
  when: is_ubuntu == True and is_arm == False

- name: Add MariaDB PPA (Ubuntu)
  apt_repository:
    repo: "deb [arch=amd64,i386] https://mirrors.evowise.com/mariadb/repo/10.2/ubuntu {{ ansible_distribution_release }} main"
    update_cache: yes
  when: is_ubuntu == True and is_arm == False

- name: Install MariaDB
  apt:
    name:
      - mariadb-client
      - mariadb-server
    state: present

- name: Disable MySQL binary logging
  template:
    src: disable-binary-logging.cnf
    dest: /etc/mysql/conf.d
    owner: root
    group: root
  when: mariadb_binary_logging_disabled

- name: Restart MySQL Server
  service:
    name: mysql
    state: restarted
    enabled: true

- name: Set root user password
  mysql_user:
    name: "{{ mysql_root_user }}"
    host: "{{ item }}"
    password: "{{ vault.db_passwords.root }}"
    check_implicit_admin: yes
    state: present
  with_items:
    - "{{ inventory_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Copy .my.cnf file with root password credentials.
  template:
    src: my.cnf.j2
    dest: ~/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: Copy config template for mb4 strings
  template:
    src: mb4strings.cnf.j2
    dest: /etc/mysql/conf.d/mb4strings.cnf
    owner: root
    group: root

- name: Delete anonymous MySQL server users
  mysql_user:
    user: ""
    host: "{{ item }}"
    state: absent
  with_items:
    - localhost
    - "{{ inventory_hostname }}"
    - "{{ ansible_hostname }}"

- name: Remove the test database
  mysql_db:
    name: test
    state: absent

- name: Restart MySQL Server
  service:
    name: mysql
    state: restarted
    enabled: true
