---
- name: Install MySQL client
  apt:
    name: mariadb-client
    state: present

- name: Install MySQL server
  apt:
    name: mariadb-server
    state: present

- name: Disable MySQL binary logging
  template:
    src: disable-binary-logging.cnf
    dest: /etc/mysql/conf.d
    owner: root
    group: root
  when: mariadb_binary_logging_disabled

- name: Restart MySQL Server
  service:
    name: mysql
    state: restarted
    enabled: true

- name: Set root user password
  mysql_user:
    name: "{{ mysql_root_user }}"
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    state: present
  with_items:
    - "{{ inventory_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Copy .my.cnf file with root password credentials.
  template:
    src: my.cnf.j2
    dest: ~/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: Copy config template for mb4 strings
  template:
    src: mb4strings.cnf.j2
    dest: /etc/mysql/conf.d/mb4strings.cnf
    owner: root
    group: root

- name: Delete anonymous MySQL server users
  mysql_user:
    user: ""
    host: "{{ item }}"
    state: absent
  with_items:
    - localhost
    - "{{ inventory_hostname }}"
    - "{{ ansible_hostname }}"

- name: Remove the test database
  mysql_db:
    name: test
    state: absent

- name: Restart MySQL Server
  service:
    name: mysql
    state: restarted
    enabled: true
