---
apps:
  myapp:
    hosts:
      - canonical: myapp.test
    ssl:
      enabled: True
      provider: self-signed
    source:
      url: git@github.com:acme/myapp.git
      version: master
    env:
      APP_URL: http://myapp.test
      APP_DEBUG: true
      APP_KEY: "{{ vault.app_key }}"
      DB_CONNECTION: pgsql
      DB_HOST: "127.0.0.1"
      DB_DATABASE: myapp
      DB_USERNAME: myapp
      DB_PASSWORD: "{{ vault.db_passwords.myapp_postgres }}"
      QUEUE_DRIVER: sync
      MAIL_DRIVER: smtp
      MAIL_HOST: mailtrap.io
      MAIL_PORT: 587
      MAIL_USERNAME: mailUsername@myapp.test
      MAIL_PASSWORD: "{{ vault.mail.password }}"
      MAIL_ENCRYPTION: tls
    passport: False
