---
- name: Install docker dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - python-docker
  tags: essential-packages
  when: docker_required

- name: Install docker-ce
  include_role:
    name: geerlingguy.docker
  when: docker_required

- name: Authenticate with docker registries
  docker_login:
    url: "{{ item.url }} | default('https://index.docker.io/v1/')"
    email: "{{ item.email }}"
    username: "{{ item.username }}"
    password: "{{ item.password }}"
  when: docker_required
  with_items: docker_registries | default([])
